export const LOAD_DIRECTORIES_SUCCESS = 'LOAD_DIRECTORIES_SUCCESS'
export const ADD_DIRECTORY_SUCCESS = 'ADD_DIRECTORY_SUCCESS'
export const UPDATE_DIRECTORY_SUCCESS = 'UPDATE_DIRECTORY_SUCCESS'
export const SELECT_DIRECTORY = 'SELECT_DIRECTORY'